import React from "react";
import AnalysisCard from "../components/AnalysisCard";
import RecommendationCard from "../components/RecommendatiaonCard";



const AnalysisPage = ({ analysis }) => {
  //
  // if (!analysis) return null;

  return (
    <section className="min-h-screen bg-slate-50 py-12">
      <div className="mx-auto max-w-7xl px-6">
        {/* Hero */}

        <div className="rounded-3xl bg-linear-to-r from-indigo-600 to-blue-600 p-10 text-white shadow-xl">
          <div className="flex flex-col items-center gap-8 md:flex-row md:justify-between">
            <div>
              <p className="text-indigo-100">AI Generated Report</p>

              <h1 className="mt-2 text-4xl font-bold">
                Ad → Landing Page Analysis
              </h1>

              <p className="mt-5 max-w-3xl text-lg text-indigo-100">
                {analysis.summary}
              </p>
            </div>

            <div className="flex h-40 w-40 items-center justify-center rounded-full bg-white text-5xl font-bold text-indigo-700 shadow-lg">
              {analysis.overallScore}
            </div>
          </div>
        </div>

        {/* Analysis */}

        <div className="mt-12">
          <h2 className="mb-6 text-3xl font-bold text-slate-800">
            Detailed Analysis
          </h2>

          <div className="grid gap-6 md:grid-cols-2">
            <AnalysisCard
              title="👤 Persona"
              section={analysis.sections.persona}
            />

            <AnalysisCard title=" Offer" section={analysis.sections.offer} />

            <AnalysisCard title=" Proof" section={analysis.sections.proof} />

            <AnalysisCard title=" CTA" section={analysis.sections.cta} />
          </div>
        </div>

        {/* Recommendations */}

        <div className="mt-14">
          <h2 className="mb-6 text-3xl font-bold text-slate-800">
            AI Recommendations
          </h2>

          <div className="space-y-6">
            {analysis.recommendations.map((item, index) => (
              <RecommendationCard
                key={index}
                recommendation={item}
                index={index}
              />
            ))}
          </div>
        </div>

        {/* Footer */}

        <div className="mt-12 rounded-2xl border border-indigo-100 bg-indigo-50 p-6">
          <h3 className="text-xl font-bold text-indigo-700">Final Verdict</h3>

          <p className="mt-3 text-slate-700">
            This report was generated by comparing the advertisement against the
            landing page content. Focus on the highest impact recommendations
            first to improve conversion rates and create a more consistent user
            experience.
          </p>
        </div>
      </div>
    </section>
  );
};

export default AnalysisPage;
